export const FAVORITES_STORAGE_KEY = "FAVORITES";
export const SETUP_COMPLETE_STORAGE_KEY = "SETUP_COMPLETE";
export const PERMISSIONS_SAVED_STORAGE_KEY = "PERMISSIONS_SAVED";
export const LOGS_LINES_STORAGE_KEY = "LOGS_LINES";
export const LOG_REFETCH_INTERVAL_STORAGE_KEY = "LOG_REFETCH_INTERVAL";
